# Generated by Django 5.0.6 on 2024-11-05 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundstockitem',
            name='supplier',
        ),
        migrations.AddField(
            model_name='inboundstock',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
            preserve_default=False,
        ),
    ]
