# Generated by Django 5.0.6 on 2024-06-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='DefaultBrand', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='DefaultDescription', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='inactive', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='DefaultType', max_length=100),
        ),
    ]
