# Generated by Django 5.0.6 on 2024-11-05 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_inboundstockitem_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundstock',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
            preserve_default=False,
        ),
    ]
