# Generated by Django 5.0.6 on 2024-11-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='representative_name',
            field=models.CharField(max_length=64),
        ),
    ]
