# Generated by Django 5.0.6 on 2024-11-05 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='barangay',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_first_name',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_last_name',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_middle_name',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='representative_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
