# Generated by Django 5.0.6 on 2024-11-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_account_name_alter_order_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=101, max_digits=10),
            preserve_default=False,
        ),
    ]
