# Generated by Django 4.2.13 on 2024-08-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_order_details_orderdetails_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_type',
            field=models.CharField(default='DefaultVehicleType', max_length=32),
        ),
    ]
