# Generated by Django 5.0.6 on 2024-11-16 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_invoice_total_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundstock',
            name='inboundStockItems',
        ),
        migrations.AddField(
            model_name='inboundstockitem',
            name='inbound_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inboundStockItems', to='api.inboundstock'),
            preserve_default=False,
        ),
    ]
