# Generated by Django 4.2.13 on 2024-11-21 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_order_account_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
