# Generated by Django 5.0.6 on 2024-11-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_account_account_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, error_messages={'blank': 'Account name cannot be empty.', 'unique': 'This account already exists.'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
