# Generated by Django 5.0.6 on 2024-09-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_inboundstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock_maximum_threshold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
