# Generated by Django 4.2.13 on 2024-11-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_customer_phone_number'),
        ('api', '0018_alter_account_account_alter_product_product_name_and_more'),
    ]

    operations = [
    ]
