# Generated by Django 5.0.6 on 2024-09-29 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_inventory_stock_maximum_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundstock',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inboundstock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inboundstock',
            name='supplier',
        ),
        migrations.CreateModel(
            name='InboundStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='inboundstock',
            name='inboundStockItems',
            field=models.ManyToManyField(related_name='inbound_stocks', to='api.inboundstockitem'),
        ),
    ]
