# Generated by Django 5.0.6 on 2024-10-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_inboundstock_inventory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='company_name',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='company',
            new_name='account',
        ),
    ]
