# Generated by Django 4.2.13 on 2024-11-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20241121_1417'),
        ('api', '0020_alter_account_account_alter_order_account'),
    ]

    operations = [
    ]
