# Generated by Django 4.2.13 on 2024-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20241129_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
