# Generated by Django 5.0.6 on 2024-10-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_company_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='stock_maximum_threshold',
        ),
    ]
