# Generated by Django 4.2.13 on 2024-11-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_account_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='date_recieved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
