# Generated by Django 4.2.13 on 2024-11-30 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_ordertracking_date_recieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertracking',
            old_name='date_recieved',
            new_name='date_received',
        ),
    ]
