# Generated by Django 5.0.6 on 2024-12-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_order_deduction_order_initial_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='initial_price',
            new_name='initial_balance',
        ),
    ]
