# Generated by Django 5.1.2 on 2024-10-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_order_employee_order_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_middle_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='representative_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
