# Generated by Django 5.0.6 on 2024-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_inboundstock_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
