# Generated by Django 5.0.6 on 2024-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_order_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundstock',
            name='reference_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
