# Generated by Django 5.0.6 on 2024-12-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_inboundstock_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
