# Generated by Django 5.0.6 on 2024-12-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_orderdetails_deductions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='deductions',
        ),
    ]
