# Generated by Django 5.0.6 on 2024-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_orderdetails_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='sku',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
