# Generated by Django 5.0.6 on 2024-10-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_product_is_deleted_alter_employee_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
