# Generated by Django 5.0.6 on 2024-10-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_product_is_deleted_inventory_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
