# Generated by Django 5.0.6 on 2024-12-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_orderdetails_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='sku',
            new_name='sku_hold',
        ),
    ]
