# Generated by Django 4.2.13 on 2024-10-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_employee_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='account',
            name='representative_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='representative_position',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='order',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_first_name',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_last_name',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_middle_name',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='representative_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
