# Generated by Django 5.0.6 on 2024-12-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_inventory_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='sku_hold',
        ),
    ]
