# Generated by Django 5.0.6 on 2024-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_orderdetails_sku_hold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
