# Generated by Django 5.0.6 on 2024-10-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_employee_is_deleted_inventory_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
    ]
