# Generated by Django 5.0.6 on 2024-12-03 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_outboundstock_outboundstockitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundstockitem',
            name='inbound_stock',
        ),
        migrations.AddField(
            model_name='outboundstockitem',
            name='outbound_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outboundStockItems', to='api.outboundstock'),
            preserve_default=False,
        ),
    ]
