# Generated by Django 5.0.6 on 2024-10-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_account_barangay_alter_account_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
