# Generated by Django 5.0.6 on 2024-10-26 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_orderdetails_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_first_name',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_last_name',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_middle_name',
            field=models.CharField(blank=True, default='', max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
