# Generated by Django 5.0.6 on 2024-12-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_outboundstockitem_inbound_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
