# Generated by Django 5.0.6 on 2024-12-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_order_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
