# Generated by Django 5.0.6 on 2024-12-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_payment_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_amount_paid',
        ),
    ]
