# Generated by Django 5.0.6 on 2024-10-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_ordertracking_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_tracking',
        ),
        migrations.AddField(
            model_name='order',
            name='order_tracking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ordertracking'),
            preserve_default=False,
        ),
    ]
