# Generated by Django 5.0.6 on 2024-12-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_order_deductions_alter_payment_deductions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='reference_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
