# Generated by Django 5.0.6 on 2024-10-26 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_orderdetails_order_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_tracking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ordertracking'),
        ),
    ]
