# Generated by Django 5.0.6 on 2024-10-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_order_order_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_tracking',
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
    ]
