# Generated by Django 5.0.6 on 2024-10-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_order_order_tracking_ordertracking_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertracking',
            old_name='date_packed',
            new_name='date_shipped',
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_tracking', to='api.order'),
        ),
    ]
