# Generated by Django 4.2.13 on 2024-10-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_rename_date_packed_ordertracking_date_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='employee_first_name',
            field=models.CharField(default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_last_name',
            field=models.CharField(default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_middle_name',
            field=models.CharField(default='', max_length=34),
        ),
    ]
