# Generated by Django 5.0.6 on 2024-10-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
