# Generated by Django 4.2.13 on 2024-10-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_order_employee_first_name_and_more'),
        ('api', '0058_alter_invoice_discounted_amount_and_more'),
    ]

    operations = [
    ]
